backend:
  name: git-gateway
  branch: main # Change to "master" if that's your default branch

media_folder: "assets/images" # Where uploaded images will be stored
public_folder: "/assets/images" # Public path to uploaded images

collections:
  - name: "blog" # Used in routes, ie.: /admin/collections/blog
    label: "Blog Posts" # Used in the UI
    folder: "blog" # The path to the folder where blog posts are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template: just the slug
    fields: # The fields for each document, matching your blog structure
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Software Development", "Mobile Apps", "SEO", "Web Development", "Technology", "Digital Marketing"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Excerpt", name: "excerpt", widget: "text", hint: "Short description that appears on blog cards"}
      - {label: "URL Slug", name: "slug", widget: "string", hint: "URL-friendly version (e.g., future-web-development-2024)"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Meta Description", name: "meta_description", widget: "text", required: false, hint: "SEO meta description"}
      - {label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "quote", "bulleted-list", "numbered-list"]}
